version: '3.8'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/api-server/docker
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local

    env_file:
      - ./backend/.env

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker-volumes/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: dynamodb-local:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=http://backend:8080/graphql
    depends_on:
      - backend

volumes:
  dynamodb_data:
