version: '3.8'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/api-server/docker
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  # フロントエンドのサービスはNext.jsを使用する予定ですが、現段階では設定を省略します。

volumes:
  dynamodb_data:
