root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api-server"
bin = "./tmp/main"
env = ["CGO_ENABLED=0", "GOOS=linux", "GOARCH=amd64"]
exclude_dir = ["node_modules", "assets", "tmp"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
